= Hello World
:hp-tags: English

=== Hey! Do you know me?

I am a passionate web developer. I love to discover new products and technologies every day. I also like to talk about my passion whether it is with newbies or with geeks.

==== My story

I was born in Zoetermeer, Netherlands on December 29, 1992. I moved to France when I was 5 and discovered Web Development at the age of 13.

I first have learned *xHTML 1.0*, *CSS 2* and *PHP 5*. My first projects were:

- *Poké-Sport*: a Pokémon community website
- *Atlamite*: a videos sharing website for me and my friends

===== WWE-FR

A Pro-Wrestling french community website. Its main goal was to post weekly and monthly videos, but also to write some news about this entertainment. This project allowed me to discover real production, Community Management, SEO and automation.

Here are some numbers about this project:

- 3 years (from 2009/10/18 to 2011/08/16)
- 220.000 users
- 1.875.000 pageviews
- 3 minutes: average session duration

===== Studies (2010-2015)

After getting my science High School diploma I went to the ENIB, a generalist Engineering School in Brest, France. This allowed me to improve my skills and discover *Python*, *Django*, *C*, *Java*, *C++*, *C#* (*Unity*), *Cordova*, *Git*...

At the time, I was convinced of one thing: *Single-Page Applications* were the future.

On January, 2014, I have begun to learn *Node.js*. I've came across *Sails.js*. A crush. Even if it has its imperfections, this *Open-Source* project is fully in tune with the times.

Since mid-mars, I have been doing my end-of-studies internship at *Orange Applications for Business* in Nantes, France. I'm working on a internal social network website with the framework I love so much.

===== Short-term future

