= My lodash/underscore.js Cheatsheet
:hp-tags: english, tech, js

This cheatsheet's aim is to simplify the lodash library docs. However the complete docs can be found at https://lodash.com/docs.

== About lodash

Lodash is a utility library delivering consistency, modularity, performance, & extras.

=== Collection

==== __.forEach(collection, [iteratee=_.identity])

Iterates over elements of `collection` invoking `iteratee` for each element. The `iteratee` is invoked with three arguments:
(value, index|key, collection). Iteratee functions may exit iteration early by explicitly returning `false`.

*Arguments*

1. `collection` `Array|Object|String`: The collection to iterate over.
2. `[iteratee=_.identity]` `Function`: The function invoked per iteration.

*Examples*

```
_([1, 2]).forEach(function(n) {
    console.log(n);
}).value();
// → logs each value from left to right and returns the array

_.forEach({ 'a': 1, 'b': 2 }, function(n, key) {
    console.log(n, key);
});
// → logs each value-key pair and returns the object (iteration order is not guaranteed)
```

==== _.includes(collection, target)

Checks if value is in `collection` using `SameValueZero for equality comparisons.

*Arguments*

1. `collection` `Array|Object|String`: The collection to search.
2. `target` `*`: The value to search for.

*Returns*

**boolean**: Returns `true` if a matching element is found, else `false`.

*Examples*

```
_.includes([1, 2, 3], 1);
// → true

_.includes([1, 2, 3], 1, 2);
// → false

_.includes({ 'user': 'fred', 'age': 40 }, 'fred');
// → true

_.includes('pebbles', 'eb');
// → true
```

==== _.pluck(collection, path)

Gets the property value of `path` from all elements in `collection`.

*Typical usage*

Log a property of an array of objects.

*Arguments*

1. `collection` `Array|Object|string`: The collection to iterate over.
2. `path` `Array|string`: The path of the property to pluck.

*Returns*

`Array`: Returns the property values.

*Examples*

```
var users = [
  { 'user': 'barney', 'age': 36 },
  { 'user': 'fred',   'age': 40 }
];

_.pluck(users, 'user');
// → ['barney', 'fred']

var userIndex = _.indexBy(users, 'user');
_.pluck(userIndex, 'age');
// → [36, 40] (iteration order is not guaranteed)
```

=== Lang

==== _.clone(value)

Creates a clone of ̀`value`.

*Typical usage*

To avoid updating an object reference.

*Arguments*

1. `value` `*`: The value to clone.

*Returns*

**boolean**: Returns `true` if a matching element is found, else `false`.

*Examples*

```
var users = [
  { 'user': 'barney' },
  { 'user': 'fred' }
];

var shallow = _.clone(users);
shallow[0] === users[0];
// → true
```